### ISSUE TITLE
Cannot target java 7 while using maven enforcer

### ISSUE THREAD

**Issue by saxonww** [versionone/VersionOne.SDK.Java.APIClient#35]
I am working on a project which targets Java 7. I get maven enforcer errors with this SDK library because it depends on version 20141113 of org.json.json, which targets java 8.

I was able to work around the issue by excluding the org.json dependency and re-declaring it:

```
        <dependency>
            <groupId>com.versionone</groupId>
            <artifactId>VersionOne.SDK.Java.APIClient</artifactId>
            <version>15.3.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.json</groupId>
                    <artifactId>json</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20140107</version>
        </dependency>
```

It's not clear yet whether the project will still work correctly or not; either way, since Java 7 is still supported, it would be nice if this library used Java 7-safe dependencies.

**Comment by jallers** [comment]
Java 7 is no longer publicly supported. We have made the decision to drop support for Java 7.
