### ISSUE TITLE
com.versionone.apiclient.exceptions.APIException: SAX Error

### ISSUE THREAD

**Issue by ddixon-mc** [versionone/VersionOne.SDK.Java.APIClient#47]
It appears that the default return format for a call to the "meta.v1/" endpoint has changed to JSON. It was previously XML.

**Comment by ddixon-mc** [comment]
For any other parties interested PR#46 (https://github.com/versionone/VersionOne.SDK.Java.APIClient/pull/46) could potential fix this issue.

**Comment by jallers** [comment]
This issue has been resolved. We appreciate the opening of this issue and the accompanying PR. It was an error in caching information in the response from meta.v1.
